// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorFatih.Data;

#nullable disable

namespace RazorFatih.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("RazorFatih.Models.HomeContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HomeContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "RazorFatih uygulamanıza hoş geldiniz. Bu sayfanın içeriğini kolayca düzenleyebilir ve uygulamanız hakkında bilgi verebilirsiniz. Gelecekteki güncellemeler ve özellikler için bizi takipte kalın!",
                            Title = "Hoş Geldiniz!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
